=== dqualizer/dqtranslator/src/test/resources/schemas/rqa_schema.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "Scenario" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string"
        },
        "path" : {
          "type" : "string"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "_class" : {
      "type" : "string"
    },
    "context" : {
      "type" : "string"
    },
    "domain_id" : {
      "type" : "string"
    },
    "environment" : {
      "type" : "string",
      "enum" : [ "PROD", "TEST", "DEV", "INT" ]
    },
    "id" : {
      "type" : "string"
    },
    "name" : {
      "type" : "string"
    },
    "runtime_quality_analysis" : {
      "type" : "object",
      "properties" : {
        "loadtests" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "properties" : {
              "_class" : {
                "type" : "string"
              },
              "artifact" : {
                "type" : "object",
                "properties" : {
                  "activity_id" : {
                    "type" : "string"
                  },
                  "system_id" : {
                    "type" : "string"
                  }
                }
              },
              "description" : {
                "type" : "string"
              },
              "id" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "parametrization" : {
                "type" : "object",
                "properties" : {
                  "path_variables" : {
                    "type" : "array",
                    "items" : {
                      "type" : "object",
                      "properties" : {
                        "name" : {
                          "type" : "string"
                        },
                        "scenarios" : {
                          "type" : "array",
                          "items" : {
                            "$ref" : "#/$defs/Scenario"
                          }
                        }
                      }
                    }
                  },
                  "payload" : {
                    "type" : "object",
                    "properties" : {
                      "name" : {
                        "type" : "string"
                      },
                      "scenarios" : {
                        "type" : "array",
                        "items" : {
                          "$ref" : "#/$defs/Scenario"
                        }
                      }
                    }
                  },
                  "request_parameter" : {
                    "type" : "array",
                    "items" : {
                      "type" : "object",
                      "properties" : {
                        "name" : {
                          "type" : "string"
                        },
                        "scenarios" : {
                          "type" : "array",
                          "items" : {
                            "$ref" : "#/$defs/Scenario"
                          }
                        }
                      }
                    }
                  },
                  "url_parameters" : {
                    "type" : "array",
                    "items" : {
                      "type" : "object",
                      "properties" : {
                        "name" : {
                          "type" : "string"
                        },
                        "scenarios" : {
                          "type" : "array",
                          "items" : {
                            "$ref" : "#/$defs/Scenario"
                          }
                        }
                      }
                    }
                  }
                }
              },
              "response_measures" : {
                "type" : "object",
                "properties" : {
                  "response_time" : {
                    "type" : "string",
                    "enum" : [ "SATISFIED", "TOLERATED", "FRUSTRATED" ]
                  }
                }
              },
              "result_metrics" : {
                "type" : "array",
                "items" : {
                  "type" : "string",
                  "enum" : [ "RESPONSE_TIME", "NINETY_PERCENTILE", "NINETY_FIVE_PERCENTILE" ]
                }
              },
              "stimulus" : {
                "type" : "object",
                "properties" : {
                  "accuracy" : {
                    "type" : "integer",
                    "format" : "int32"
                  },
                  "load_profile" : {
                    "type" : "string",
                    "enum" : [ "LOAD_PEAK", "LOAD_INCREASE", "CONSTANT_LOAD" ]
                  },
                  "type" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        },
        "monitoring_definition" : {
          "type" : "array",
          "items" : {
            "type" : "object",
            "properties" : {
              "id" : {
                "type" : "string"
              },
              "measurement_name" : {
                "type" : "string"
              },
              "measurement_type" : {
                "type" : "string",
                "enum" : [ "EXECUTION_TIME", "EXECUTION_COUNT", "VALUE_INSPECTION" ]
              },
              "measurement_unit" : {
                "type" : "string"
              },
              "target" : {
                "type" : "string"
              }
            }
          }
        },
        "resilience_definition" : {
          "type" : "array",
          "items" : {
            "type" : "object"
          }
        }
      }
    },
    "version" : {
      "type" : "string"
    }
  }
}

=== dqualizer/dqtranslator/src/test/resources/mock/RQA.json
{
  "$schema": "./../schemas/rqa_schema.json",
  "id": "ee5237bd-4f3c-4a6c-a0eb-c9615465dfcd",
  "name": "Example RQA",
  "environment": "DEV",
  "context": "af6a8837-7e4c-40b2-9494-aadec45fb2a4",
  "domain_id": "af6a8837-7e4c-40b2-9494-aadec45fb2a4",
  "version": "0.0.1",
  "runtime_quality_analysis": {
    "loadtests": [],
    "resilience_definition": [],
    "monitoring_definition": [
      {
        "id": "63cf2522-bed9-4a92-bc54-542c43c60c38",
        "target": "Activity 5",
        "measurement_name": "MasterDataFiscalYearDataLength",
        "measurement_type": "VALUE_INSPECTION",
        "measurement_unit": "",
        "inspected_value": "Masterdata.Length"
      },
      {
        "id": "538e6899-55c4-42bb-86c7-97a21f76ada7",
        "target": "Activity 5",
        "measurement_name": "MasterDataSearchExecutionTime",
        "measurement_type": "EXECUTION_TIME",
        "measurement_unit": "ms"
      }
    ]
  }
}
